alter table profiles enable row level security;
alter table stores enable row level security;
alter table store_members enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table inventory enable row level security;
alter table inventory_lists enable row level security;
alter table inventory_list_items enable row level security;
alter table audit_logs enable row level security;
create or replace function is_adm() returns boolean as $$ select exists(select 1 from profiles where id=auth.uid() and role='adm' and active=true); $$ language sql stable security definer;
create or replace function belongs_to_store(p_store_id uuid) returns boolean as $$ select exists(select 1 from store_members where store_id=p_store_id and user_id=auth.uid()); $$ language sql stable security definer;
create policy "profiles_select_own_or_adm" on profiles for select using(id=auth.uid() or is_adm());
create policy "profiles_update_own_or_adm" on profiles for update using(id=auth.uid() or is_adm());
create policy "profiles_insert_adm_only" on profiles for insert with check(is_adm() or id=auth.uid());
create policy "stores_select_member_or_adm" on stores for select using(is_adm() or belongs_to_store(id));
create policy "stores_write_adm_only" on stores for insert with check(is_adm());
create policy "stores_update_adm_only" on stores for update using(is_adm());
create policy "members_select_own_or_adm" on store_members for select using(user_id=auth.uid() or is_adm());
create policy "members_write_adm_only" on store_members for insert with check(is_adm());
create policy "members_delete_adm_only" on store_members for delete using(is_adm());
create policy "categories_select_authenticated" on categories for select using(auth.uid() is not null);
create policy "categories_write_adm_only" on categories for insert with check(is_adm());
create policy "categories_update_adm_only" on categories for update using(is_adm());
create policy "products_select_authenticated" on products for select using(auth.uid() is not null);
create policy "products_write_adm_only" on products for insert with check(is_adm());
create policy "products_update_adm_only" on products for update using(is_adm());
create policy "inventory_select_member_or_adm" on inventory for select using(is_adm() or belongs_to_store(store_id));
create policy "inventory_update_member_or_adm" on inventory for update using(is_adm() or belongs_to_store(store_id));
create policy "inventory_insert_member_or_adm" on inventory for insert with check(is_adm() or belongs_to_store(store_id));
create policy "lists_select_member_or_adm" on inventory_lists for select using(is_adm() or belongs_to_store(store_id));
create policy "lists_write_member_or_adm" on inventory_lists for insert with check(is_adm() or belongs_to_store(store_id));
create policy "lists_update_member_or_adm" on inventory_lists for update using(is_adm() or belongs_to_store(store_id));
create policy "list_items_select_via_list" on inventory_list_items for select using(is_adm() or exists(select 1 from inventory_lists l where l.id=list_id and belongs_to_store(l.store_id)));
create policy "list_items_write_via_list" on inventory_list_items for insert with check(is_adm() or exists(select 1 from inventory_lists l where l.id=list_id and belongs_to_store(l.store_id)));
create policy "list_items_update_via_list" on inventory_list_items for update using(is_adm() or exists(select 1 from inventory_lists l where l.id=list_id and belongs_to_store(l.store_id)));
create policy "audit_select_member_or_adm" on audit_logs for select using(is_adm() or belongs_to_store(store_id));
create policy "audit_insert_member_or_adm" on audit_logs for insert with check(is_adm() or belongs_to_store(store_id) or store_id is null);
